stages:
  - common_build
  - core_build
  - player_build
  - cleanup_build
common_build_job:
  stage: common_build
  script:
  - cd Common
  - cd Exceptions
  - rename 'y/A-Z/a-z/' *.h
  - rename 'y/A-Z/a-z/' *.cpp
  - cd ..
  - qmake Common.pro -r -spec linux-g++-64 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11" "CONFIG += warn_off"
  - make
  only:
    - master
    - develop
core_build_job:
  stage: core_build
  script:
  - cd Core
  - qmake Core.pro -r -spec linux-g++-64 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11" "CONFIG += warn_off"
  - make
  only:
    - master
    - develop
player_build_job:
  stage: player_build
  script:
  - qmake ENPlayer.pro -r -spec linux-g++-64 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11" "CONFIG += warn_off"
  - make
  only:
    - master
    - develop
cleanup_build_job:
  stage: cleanup_build
  script:
  - qmake ENPlayer.pro -r -spec linux-g++-64 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11" "CONFIG += warn_off"
  - make clean
  when: on_failure
  only:
    - master
    - develop