stages:
  - common_core_build
  - player_build
  - cleanup_build
common_core_build_job:
  stage: common_core_build
  script:
  - cd Common
  - qmake Common.pro -r -spec linux-g++-64 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11" "CONFIG += warn_off"
  - make
  - cd ..
  - cd Core
  - qmake Core.pro -r -spec linux-g++-64 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11" "CONFIG += warn_off"
  - make
  only:
    - develop
player_build_job:
  stage: player_build
  script:
  - cp /home/gitlab-runner/builds/56caa0c3/0/young_developer/subparser/libSubParser.a Core/3dparty/sub-parser/lib/
  - cp /home/vlc-qt-0.10.0/build/src/core/libvlc-qt.a Core/3dparty/libvlc-qt/lib/libvlc-qt.dll.a
  - cp /home/vlc-qt-0.10.0/build/src/widgets/libvlc-qt-widgets.a Core/3dparty/libvlc-qt/lib/libvlc-qt-widgets.dll.a
  - cp /home/vlc-qt-0.10.0/build/src/qml/libvlc-qt-qml.a Core/3dparty/libvlc-qt/lib/libvlc-qt-qml.dll.a
  - qmake ENPlayer.pro -r -spec linux-g++-64 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11" "CONFIG += warn_off"
  - make
  only:
    - master
    - develop
cleanup_build_job:
  stage: cleanup_build
  script:
  - qmake ENPlayer.pro -r -spec linux-g++-64 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11" "CONFIG += warn_off"
  - make clean
  when: on_failure
  only:
    - master
    - develop