stages:
  - common_build
  - core_build
  - player_build
  - cleanup_build
common_build_job:
  stage: common_build
  script:
  - cd Common
  - for a_file in *;do mv -v $a_file `echo $a_file | tr [:upper:] [:lower:]` ;done;
  - qmake common.pro -r -spec linux-g++-64 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11"
  - make
  only:
    - master
    - develop
core_build_job:
  stage: core_build
  script:
  - cd Core
  - for a_file in *;do mv -v $a_file `echo $a_file | tr [:upper:] [:lower:]` ;done;
  - qmake core.pro -r -spec linux-g++-64 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11"
  - make
  only:
    - master
    - develop
player_build_job:
  stage: player_build
  script:
  - for a_file in *;do mv -v $a_file `echo $a_file | tr [:upper:] [:lower:]` ;done;
  - qmake enplayer.pro -r -spec linux-g++-64 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11"
  - make
  only:
    - master
    - develop
cleanup_build_job:
  stage: cleanup_build
  script:
  - for a_file in *;do mv -v $a_file `echo $a_file | tr [:upper:] [:lower:]` ;done;
  - qmake enplayer.pro -r -spec linux-g++-64 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11"
  - make clean
  when: on_failure
  only:
    - master
    - develop